import { TranslationStrings } from '../translations';

export const ruTranslations: TranslationStrings = {
  common: {
    loading: 'Загрузка...',
    error: 'Ошибка',
    retry: 'Повторить',
    close: 'Закрыть',
    cancel: 'Отмена',
    confirm: 'Подтвердить',
    continue: 'Продолжить',
    back: 'Назад',
    next: 'Далее',
    previous: 'Предыдущий',
    search: 'Поиск',
    filter: 'Фильтр',
    clear: 'Очистить',
    save: 'Сохранить',
    edit: 'Редактировать',
    delete: 'Удалить',
    add: 'Добавить',
    view: 'Просмотр',
    contact: 'Контакт',
    phone: 'Телефон',
    email: 'Электронная почта',
    location: 'Местоположение',
    price: 'Цена',
    currency: 'Валюта',
    year: 'Год',
    make: 'Марка',
    model: 'Модель',
    mileage: 'Пробег',
    condition: 'Состояние',
    features: 'Особенности',
    description: 'Описание',
    images: 'Изображения',
    seller: 'Продавец',
    dealer: 'Дилер',
    private: 'Частный',
    yes: 'Да',
    no: 'Нет',
    menu: 'Меню',
    new: 'Новый',
    certified: 'Сертифицированный',
    vehicle: 'транспорт',
    message: 'Сообщение',
    default: 'По умолчанию',
    secondary: 'Вторичный',
    outline: 'Контур',
    ghost: 'Призрак',
    link: 'Ссылка',
    destructive: 'Разрушительный',
    small: 'Маленький',
    large: 'Большой',
    option: 'Опция',
    sending: 'Отправка...',
  },

  // Forms - validation, labels, placeholders, actions
  forms: {
    validation: {
      nameRequired: 'Имя обязательно',
      emailRequired: 'Email обязателен',
      emailInvalid: 'Пожалуйста, введите действительный email',
      phoneRequired: 'Номер телефона обязателен',
      messageRequired: 'Сообщение обязательно',
      loanAmountRequired: 'Сумма кредита обязательна',
      annualIncomeRequired: 'Годовой доход обязателен',
      creditScoreRequired: 'Кредитный рейтинг обязателен',
      employmentStatusRequired: 'Статус занятости обязателен',
      yearsAtJobRequired: 'Стаж на текущей работе обязателен',
      monthlyExpensesRequired: 'Ежемесячные расходы обязательны',
      makeRequired: 'Марка обязательна',
      modelRequired: 'Модель обязательна',
      yearRequired: 'Год обязателен',
      yearInvalid: 'Недействительный год',
      mileageRequired: 'Пробег обязателен',
      mileageNegative: 'Пробег не может быть отрицательным',
      dateRequired: 'Пожалуйста, выберите дату',
      timeRequired: 'Пожалуйста, выберите время',
    },
    labels: {
      fullName: 'Полное имя',
      email: 'Email',
      phone: 'Номер телефона',
      message: 'Сообщение',
    },
    placeholders: {
      enterFullName: 'Введите ваше полное имя',
      enterEmail: 'Введите ваш email',
      enterPhone: 'Введите ваш номер телефона',
      contactMessage: 'Здравствуйте, я заинтересован в {year} {make} {model}. Пожалуйста, свяжитесь со мной для получения подробностей.',
    },
    actions: {
      sendMessage: 'Отправить сообщение',
    },
  },

  // Modals - titles, descriptions, success messages
  modals: {
    contactCar: {
      title: 'Связаться с продавцом',
      description: 'Отправить сообщение об этом автомобиле',
      successTitle: 'Сообщение успешно отправлено!',
      successDescription: 'Ваше сообщение отправлено продавцу. Они свяжутся с вами в ближайшее время.',
    },
    financing: {
      title: 'Получить предварительное одобрение финансирования',
      description: 'Получите предварительное одобрение автомобильного финансирования за минуты',
      badges: {
        financingAvailable: 'Финансирование Доступно',
      },
      employmentStatus: {
        retired: 'Пенсионер',
        student: 'Студент',
        unemployed: 'Безработный',
      },
      placeholders: {
        enterFullName: 'Введите ваше полное имя',
        enterPhone: 'Введите ваш номер телефона',
        enterEmail: 'Введите ваш email адрес',
        enterLoanAmount: 'Введите сумму кредита',
        enterAnnualIncome: 'Введите годовой доход',
        enterMonthlyExpenses: 'Введите ежемесячные расходы',
        selectRange: 'Выберите диапазон',
        selectStatus: 'Выберите статус',
        selectDuration: 'Выберите срок',
      },
      validation: {
        validEmail: 'Пожалуйста, введите действительный email',
        monthlyExpensesRequired: 'Ежемесячные расходы обязательны',
      },
    },
    scheduleTestDrive: {
      title: 'Запланировать тест-драйв',
      description: 'Забронировать встречу для тест-драйва этого автомобиля',
      badge: 'Тест-драйв доступен',
      labels: {
        fullName: 'Полное имя',
        email: 'Email',
        phone: 'Номер телефона',
        preferredDate: 'Предпочтительная дата',
        preferredTime: 'Предпочтительное время',
        specialRequests: 'Специальные пожелания',
      },
      placeholders: {
        enterFullName: 'Введите ваше полное имя',
        enterEmail: 'Введите ваш email адрес',
        enterPhone: 'Введите ваш номер телефона',
        selectDate: 'Выберите предпочтительную дату',
        selectTime: 'Выберите предпочтительное время',
        enterRequests: 'Есть особые пожелания или вопросы?',
      },
      validation: {
        emailInvalid: 'Пожалуйста, введите действительный email',
        dateRequired: 'Пожалуйста, выберите предпочтительную дату',
        timeRequired: 'Пожалуйста, выберите предпочтительное время',
      },
      success: {
        title: 'Тест-драйв запланирован!',
        description: 'Ваш запрос на тест-драйв отправлен продавцу. Они свяжутся с вами для подтверждения встречи.',
      },
      actions: {
        cancel: 'Отмена',
        schedule: 'Запланировать тест-драйв',
        scheduling: 'Планирование...',
      },
    },
    tradeIn: {
      title: 'Оценщик Trade-In',
      description: 'Получите мгновенную оценку стоимости обмена вашего текущего автомобиля',
      tabs: {
        vehicleInfo: 'Информация об автомобиле',
        condition: 'Состояние',
        results: 'Результаты'
      },
      form: {
        labels: {
          make: 'Марка',
          model: 'Модель',
          year: 'Год',
          mileage: 'Пробег (км)',
          condition: 'Общее состояние',
          accident: 'История аварий',
          serviceHistory: 'История обслуживания',
          modifications: 'Модификации'
        },
        placeholders: {
          selectMake: 'Выберите марку',
          selectModel: 'Выберите модель',
          selectYear: 'Выберите год',
          enterMileage: 'Введите пробег в километрах',
          selectCondition: 'Выберите общее состояние',
          selectAccidentHistory: 'Выберите историю аварий',
          selectServiceHistory: 'Выберите историю обслуживания',
          selectModifications: 'Выберите модификации'
        },
        options: {
          condition: {
            excellent: 'Отличное',
            good: 'Хорошее',
            fair: 'Удовлетворительное',
            poor: 'Плохое'
          },
          accident: {
            none: 'Без аварий',
            minor: 'Мелкая авария',
            major: 'Серьезная авария',
            multiple: 'Несколько аварий'
          },
          serviceHistory: {
            complete: 'Полная история обслуживания',
            partial: 'Частичная история обслуживания',
            none: 'Нет истории обслуживания'
          },
          modifications: {
            none: 'Без модификаций',
            minor: 'Небольшие модификации',
            major: 'Значительные модификации'
          }
        }
      },
      validation: {
        makeRequired: 'Пожалуйста, выберите марку',
        modelRequired: 'Пожалуйста, выберите модель',
        yearRequired: 'Пожалуйста, выберите год',
        mileageRequired: 'Пожалуйста, введите пробег',
        mileageInvalid: 'Пожалуйста, введите действительный пробег',
        conditionRequired: 'Пожалуйста, выберите общее состояние',
        accidentRequired: 'Пожалуйста, выберите историю аварий',
        serviceRequired: 'Пожалуйста, выберите историю обслуживания',
        modificationsRequired: 'Пожалуйста, выберите модификации'
      },
      results: {
        title: 'Ваша оценка Trade-In',
        estimatedValue: 'Оценочная стоимость обмена',
        range: 'Диапазон',
        confidence: 'Уровень достоверности',
        confidenceLevels: {
          high: 'Высокий',
          medium: 'Средний',
          low: 'Низкий'
        },
        factors: {
          title: 'Факторы, влияющие на вашу оценку',
          positive: 'Положительные факторы',
          negative: 'Отрицательные факторы',
          neutral: 'Нейтральные факторы'
        },
        recommendations: {
          title: 'Рекомендации',
          maintenance: 'Рассмотрите решение проблем с техническим обслуживанием перед обменом',
          documentation: 'Соберите все сервисные записи и документацию',
          inspection: 'Получите профессиональную инспекцию для точной оценки',
          timing: 'Учитывайте время рынка для вашей конкретной марки и модели'
        },
        disclaimer: {
          title: 'Важная оговорка',
          text: 'Это расчетная стоимость, основанная на предоставленной информации. Фактические стоимости обмена могут варьироваться в зависимости от политики дилера, текущих рыночных условий и физического осмотра автомобиля. Мы рекомендуем получить предложения от нескольких дилеров для наиболее точной оценки.'
        }
      },
      actions: {
        calculate: 'Рассчитать оценку',
        recalculate: 'Пересчитать',
        getQuotes: 'Получить предложения дилеров',
        startOver: 'Начать заново',
        close: 'Закрыть',
        next: 'Далее',
        previous: 'Назад'
      },
      loading: {
        calculating: 'Расчет вашей оценки...',
        fetchingData: 'Получение рыночных данных...'
      }
    },
    badges: {
      new: 'Новый',
      certified: 'Сертифицированный',
    },
  },

  hero: {
    title: 'Найдите Ваш Идеальный Автомобиль',
    subtitle: 'Ищите среди тысяч качественных подержанных автомобилей',
    searchButton: 'Найти Автомобили',
    advancedSearch: 'Расширенный Поиск',
    vehicleTypes: {
      cars: 'Автомобили',
      motorbikes: 'Мотоциклы',
      trucks: 'Грузовики',
    },
    searchForm: {
      make: 'Марка',
      model: 'Модель',
      priceFrom: 'Цена От',
      priceTo: 'Цена До',
      yearFrom: 'Год От',
      mileage: 'Пробег (км)',
      location: 'Местоположение',
      anyMake: 'Любая Марка',
      anyModel: 'Любая Модель',
      minPrice: 'Минимальная Цена',
      maxPrice: 'Максимальная Цена',
      minYear: 'Минимальный Год',
      anyYear: 'Любой Год',
      anyMileage: 'Любой Пробег',
      maxMileage: 'Максимальный Пробег',
      noMin: 'Без Минимума',
      noMax: 'Без Максимума',
      enterLocation: 'Введите город или почтовый индекс',
    },
    availableCars: 'Более 50,000 автомобилей доступны по всей стране',
  },

  // Last Search Section
  lastSearch: {
    title: 'Последний поиск',
    description: 'Автомобили BMW от €20,000 - €35,000, годы 2019-2022 • Найдено 247 результатов',
    viewMore: 'Показать ещё',
    matchPercentage: '% совпадение',
  },

  // Interesting Suggestions Section
  suggestions: {
    title: 'Это может вас заинтересовать',
    description: 'Свежие объявления BMW, соответствующие вашим критериям • Недавно добавлены на платформу',
    seeMore: 'Показать больше предложений',
    daysAgo: 'д назад',
  },

  // Popular Brands Section
  brands: {
    title: 'Покупки по брендам',
    description: 'Просматривайте автомобили от самых популярных производителей',
    carsCount: 'автомобилей',
  },

  header: {
    welcome: 'Добро пожаловать в CarMarket365',
    signIn: 'Войти',
    signOut: 'Выйти',
    myAccount: 'Мой аккаунт',
    dashboard: 'Панель управления',
    home: 'Главная',
    browseCars: 'Просмотр автомобилей',
    sellCar: 'Продать автомобиль',
    savedCars: 'Сохранённые автомобили',
    financing: 'Финансирование',
    about: 'О нас',
    contact: 'Контакты',
    faq: 'Часто задаваемые вопросы',
    help: 'Помощь',
  },

  cars: {
    title: 'Автомобили на продажу',
    searchPlaceholder: 'Марка, модель или ключевое слово',
    noResults: 'Не найдено автомобилей, соответствующих вашим критериям',
    resultsCount: 'Найдено {count} транспортных средств',
    viewDetails: 'Просмотр деталей',
    contactSeller: 'Связаться с продавцом',
    saveToFavorites: 'Сохранить в избранное',
    removeFromFavorites: 'Удалить из избранного',
    carDetails: 'Детали автомобиля',
    specifications: 'Характеристики',
    fuelType: 'Тип топлива',
    transmission: 'Коробка передач',
    bodyType: 'Тип кузова',
    exteriorColor: 'Внешний цвет',
    interiorColor: 'Цвет салона',
    drivetrain: 'Привод',
    vin: 'VIN номер',
    inspection: 'Осмотр',
    history: 'История',
    financing: 'Финансирование',
    testDrive: 'Тест-драйв',
    makeOffer: 'Сделать предложение',
    featured: 'Рекомендуемые объявления',
    handpicked: 'Отобранные автомобили для вас',
    discover: 'Откройте для себя наши тщательно отобранные премиум автомобили',
    allCars: 'Все автомобили',
    newCars: 'Новые автомобили',
    certifiedPreOwned: 'Сертифицированные б/у',
    electric: 'Электрические',
    luxury: 'Люксовые',
    viewAllCars: 'Посмотреть все автомобили',
  },

  filters: {
    title: 'Фильтры поиска',
    anyMake: 'Любая марка',
    anyModel: 'Любая модель',
    anyYear: 'Любой год',
    priceRange: 'Диапазон цен',
    priceMin: 'Минимальная цена',
    priceMax: 'Максимальная цена',
    yearRange: 'Диапазон лет',
    yearMin: 'Минимальный год',
    yearMax: 'Максимальный год',
    mileageMax: 'Максимальный пробег',
    location: 'Местоположение',
    fuelTypes: 'Тип топлива',
    transmissionTypes: 'Коробка передач',
    bodyTypes: 'Тип кузова',
    condition: 'Состояние',
    applyFilters: 'Применить фильтры',
    clearFilters: 'Очистить фильтры',
  },

  auth: {
    signIn: 'Войти',
    signUp: 'Регистрация',
    signOut: 'Выйти',
    email: 'Электронная почта',
    password: 'Пароль',
    confirmPassword: 'Подтвердить пароль',
    firstName: 'Имя',
    lastName: 'Фамилия',
    phoneNumber: 'Номер телефона',
    rememberMe: 'Запомнить меня',
    forgotPassword: 'Забыли пароль?',
    createAccount: 'Создать аккаунт',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    dontHaveAccount: 'Ещё нет аккаунта?',
    loginWith: 'Или продолжить с',
    registerAs: 'Зарегистрироваться как',
    privatePerson: 'Частное лицо',
    dealerAccount: 'Аккаунт дилера',
    userType: 'Я',
    
    // SignIn page specific
    backToHome: 'Назад на главную',
    signInToAccount: 'Войти в ваш аккаунт',
    welcomeBack: 'Добро пожаловать',
    enterCredentials: 'Введите ваши данные для доступа к аккаунту',
    privatePersonDescription: 'Покупайте или продавайте свой автомобиль',
    dealerDescription: 'Профессиональный продавец',
    pro: 'Профи',
    enterYourEmail: 'Введите ваш email',
    enterYourPassword: 'Введите ваш пароль',
    signingIn: 'Выполняется вход...',
    orContinueWith: 'Или продолжить с',
    google: 'Google',
    facebook: 'Facebook',
    createPrivateAccount: 'Создать личный аккаунт',
    registerAsDealer: 'Зарегистрироваться как дилер',
    dealerBenefits: 'Преимущества дилера',
    professionalDashboard: '• Профессиональная панель дилера',
    inventoryManagement: '• Расширенное управление запасами',
    customerTracking: '• Отслеживание клиентских запросов',
    enhancedVisibility: '• Повышенная видимость объявлений',
    analyticsInsights: '• Аналитика и статистика',
    
    // UserSignUp page specific
    createYourAccount: 'Создайте ваш аккаунт',
    joinThousands: 'Присоединяйтесь к тысячам автолюбителей',
    privateAccount: 'Личный аккаунт',
    buyAndSellCars: 'Покупайте и продавайте автомобили, сохраняйте избранное и управляйте объявлениями',
    fullName: 'Полное имя',
    enterFullName: 'Введите ваше полное имя',
    emailAddress: 'Адрес электронной почты',
    createStrongPassword: 'Создайте надёжный пароль',
    confirmYourPassword: 'Подтвердите ваш пароль',
    mustBeCharacters: 'Должно быть не менее 8 символов',
    agreeToTerms: 'Я согласен с',
    termsOfService: 'Условиями обслуживания',
    and: 'и',
    privacyPolicy: 'Политикой конфиденциальности',
    creatingAccount: 'Создание аккаунта...',
    wantSellAsDealer: 'Хотите продавать автомобили как дилер?',
    createDealerAccount: 'Создать аккаунт дилера',
    joinCommunityText: 'Создавая аккаунт, вы присоединяетесь к нашему сообществу автолюбителей и соглашаетесь с правилами платформы.',
    
    // Error messages for signup
    pleaseAgreeTerms: 'Пожалуйста, согласитесь с условиями',
    passwordsNotMatch: 'Пароли не совпадают',
    passwordMinLength: 'Пароль должен содержать не менее 8 символов',
    registrationFailed: 'Регистрация не удалась',
    
    // DealerSignUp page specific
    backToSignIn: 'Назад к входу',
    dealerRegistration: 'Регистрация дилера',
    joinCarMarketDealer: 'Присоединиться к CarMarket365 как профессиональный дилер',
    businessInformation: 'Информация о бизнесе',
    tellUsAboutBusiness: 'Расскажите нам о вашем автосалоне или бизнесе',
    businessName: 'Название компании',
    businessNamePlaceholder: 'Название вашей компании ООО',
    businessType: 'Тип бизнеса',
    selectBusinessType: 'Выберите тип бизнеса',
    carDealership: 'Автосалон',
    usedCarLot: 'Площадка подержанных автомобилей',
    autoTrader: 'Автотрейдер',
    carBroker: 'Автоброкер',
    rentalCompany: 'Прокатная компания',
    other: 'Другое',
    vatNumber: 'НДС номер',
    vatNumberPlaceholder: 'RU123456789',
    taxId: 'Налоговый номер',
    optional: 'Опционально',
    yearEstablished: 'Год основания',
    selectYear: 'Выберите год',
    businessDescription: 'Описание бизнеса',
    businessDescriptionPlaceholder: 'Опишите ваш бизнес, специализации и услуги...',
    contactPerson: 'Контактное лицо',
    primaryContactInfo: 'Основная контактная информация для вашего бизнеса',
    position: 'Должность',
    positionPlaceholder: 'например, Владелец, Менеджер по продажам',
    businessEmail: 'Корпоративный email',
    businessEmailPlaceholder: 'business@example.com',
    businessAddress: 'Адрес бизнеса',
    dealershipLocation: 'Физическое местоположение вашего автосалона',
    streetAddress: 'Уличный адрес',
    streetAddressPlaceholder: 'ул. Бизнес-центр, 123',
    city: 'Город',
    cityPlaceholder: 'Москва',
    stateRegion: 'Регион/Область',
    stateRegionPlaceholder: 'Московская область',
    postalCode: 'Почтовый индекс',
    postalCodePlaceholder: '101000',
    country: 'Страна',
    selectCountry: 'Выберите страну',
    germany: 'Германия',
    austria: 'Австрия',
    switzerland: 'Швейцария',
    netherlands: 'Нидерланды',
    belgium: 'Бельгия',
    france: 'Франция',
    italy: 'Италия',
    spain: 'Испания',
    accountSetup: 'Настройка аккаунта',
    createSecureDealerAccount: 'Создайте ваш защищённый аккаунт дилера',
    termsAndAgreements: 'Условия и соглашения',
    acceptTermsConditions: 'Я принимаю Условия и положения',
    agreeToTermsAndDealer: 'Вы соглашаетесь с нашими Условиями обслуживания и Соглашением с дилером.',
    acceptPrivacyPolicy: 'Я принимаю Политику конфиденциальности',
    understandDataCollection: 'Вы понимаете, как мы собираем и используем ваши данные.',
    receiveMarketingCommunications: 'Я хотел бы получать маркетинговые коммуникации',
    getUpdatesFeatures: 'Получайте обновления о новых функциях и бизнес-возможностях.',
    alreadyHaveAccountSignIn: 'Уже есть аккаунт? Войти',
    
    // Validation error messages for dealer signup
    businessNameRequired: 'Название компании обязательно',
    businessTypeRequired: 'Тип бизнеса обязателен',
    vatNumberRequired: 'НДС номер обязателен',
    firstNameRequired: 'Имя обязательно',
    lastNameRequired: 'Фамилия обязательна',
    emailRequired: 'Email обязателен',
    phoneRequired: 'Номер телефона обязателен',
    streetRequired: 'Уличный адрес обязателен',
    cityRequired: 'Город обязателен',
    postalCodeRequired: 'Почтовый индекс обязателен',
    passwordRequired: 'Пароль обязателен',
    confirmPasswordRequired: 'Пожалуйста, подтвердите пароль',
    validEmailRequired: 'Пожалуйста, введите действительный адрес электронной почты',
    validVatNumber: 'Пожалуйста, введите действительный НДС номер (например, RU123456789)',
    passwordMinEightChars: 'Пароль должен содержать не менее 8 символов',
    acceptTermsRequired: 'Вы должны принять условия и положения',
    acceptPrivacyRequired: 'Вы должны принять политику конфиденциальности',
  },

  sell: {
    title: 'Продайте свой автомобиль',
    sellYourCar: 'Продайте свой транспорт',
    carInformation: 'Информация об автомобиле',
    uploadPhotos: 'Загрузить фотографии',
    setPrice: 'Установить цену',
    contactInformation: 'Контактная информация',
    publish: 'Опубликовать',
    draft: 'Сохранить как черновик',
    preview: 'Предварительный просмотр',
    required: 'Обязательно',
    optional: 'Опционально',
    addPhotos: 'Добавить фотографии',
    removePhoto: 'Удалить фотографию',
    mainPhoto: 'Главная фотография',
    additionalInfo: 'Дополнительная информация',
    sellerNotes: 'Заметки продавца',
    
    // Step titles
    steps: {
      vehicleType: 'Тип транспорта',
      basicInfo: 'Основная информация',
      details: 'Детали',
      photosAndContact: 'Фото и контакты',
    },
    
    // Vehicle type selection
    vehicleTypes: {
      car: {
        name: 'Автомобиль',
        description: 'Седаны, кроссоверы, купе, хэтчбеки',
      },
      truck: {
        name: 'Грузовик',
        description: 'Пикапы, коммерческий транспорт',
      },
      motorbike: {
        name: 'Мотоцикл',
        description: 'Мотоциклы, скутеры, квадроциклы',
      },
    },
    
    // Headers and descriptions
    headers: {
      vehicleTypeQuestion: 'Какой тип транспорта вы продаете?',
      basicInformation: 'Основная информация',
      basicInfoDescription: 'Расскажите нам о вашем {vehicleType}',
      additionalDetails: 'Дополнительные детали',
      additionalDetailsDescription: 'Добавьте больше деталей о вашем {vehicleType}',
      photosAndContact: 'Фотографии и контактная информация',
      photosAndContactDescription: 'Добавьте фотографии и контактные данные',
    },
    
    // Form fields and labels
    fields: {
      make: 'Марка',
      model: 'Модель',
      year: 'Год',
      mileage: 'Пробег',
      condition: 'Состояние',
      fuelType: 'Тип топлива',
      transmission: 'Коробка передач',
      exteriorColor: 'Внешний цвет',
      interiorColor: 'Внутренний цвет',
      askingPrice: 'Запрашиваемая цена',
      featuresAndOptions: 'Характеристики и опции',
      description: 'Описание',
      vehiclePhotos: 'Фотографии транспорта',
      contactName: 'Имя для связи',
      phoneNumber: 'Номер телефона',
      emailAddress: 'Адрес электронной почты',
      location: 'Местоположение',
    },
    
    // Placeholders
    placeholders: {
      selectMake: 'Выберите марку',
      enterModel: 'Введите модель',
      selectYear: 'Выберите год',
      selectCondition: 'Выберите состояние',
      enterMileage: 'Введите пробег',
      selectFuelType: 'Выберите тип топлива',
      selectTransmission: 'Выберите коробку передач',
      exteriorColorExample: 'напр. белый, черный, серебристый',
      interiorColorExample: 'напр. черный, бежевый, серый',
      priceExample: '25.000',
      descriptionExample: 'Опишите состояние вашего транспорта, историю и дополнительные детали...',
      yourFullName: 'Ваше полное имя',
      phoneExample: '(8) 123-456-78',
      emailExample: 'ваш.email@пример.ru',
      cityState: 'Город, Область',
      yourName: 'Ваше имя',
      yourPhoneNumber: 'Ваш номер телефона',
      yourEmail: 'Ваш email',
      cityCountry: 'Город, Страна',
      enterAskingPrice: 'Введите желаемую цену',
      describeYourVehicle: 'Опишите ваш автомобиль...',
      selectFuel: 'Выберите тип топлива',
      selectTransmissionType: 'Выберите тип трансмиссии',
      choosePhotos: 'Выберите фотографии',
    },
    
    // Headers
    headers: {
      vehicleTypeQuestion: 'Какой тип транспорта вы продаете?',
      basicInformation: 'Основная информация',
      basicInfoDescription: 'Расскажите нам о вашем {vehicleType}',
      additionalDetails: 'Дополнительные детали',
      additionalDetailsDescription: 'Добавьте больше деталей о вашем {vehicleType}',
      photosAndContact: 'Фотографии и контактная информация',
      photosAndContactDescription: 'Добавьте фотографии и ваши контактные данные',
      vehicleDetails: 'Детали автомобиля',
      photosAndContactInfo: 'Фотографии и контактная информация',
      uploadVehiclePhotos: 'Загрузить фотографии автомобиля',
      addUpToTenPhotos: 'Добавить до 10 фотографий',
    },
    
    // Button labels
    buttons: {
      nextStep: 'Следующий шаг',
      previous: 'Предыдущий',
      createListing: 'Создать объявление',
    },
    
    // Preview section
    preview: {
      title: 'Предварительный просмотр',
      yourVehicle: 'Ваш транспорт',
      milesLabel: 'километров',
      priceLabel: 'Цена',
      photosCount: '{count} фотографи{plural}',
      photo: 'я',
      photos: 'й',
    },
    
    // Photo upload
    photos: {
      instruction: 'Добавьте до 10 высококачественных фотографий вашего транспорта. Первая фотография будет основным изображением в результатах поиска.',
      selected: '{count} фотографи{plural} выбрано',
      photo: 'я',
      photos: 'й',
    },
    
    // Vehicle makes (can be expanded)
    makes: ['Toyota', 'Honda', 'Ford', 'Chevrolet', 'BMW', 'Mercedes-Benz', 'Audi', 'Volkswagen', 'Nissan', 'Hyundai'],
    
    // Fuel types
    fuelTypes: {
      gasoline: 'Бензин',
      electric: 'Электро',
      hybrid: 'Гибрид',
      diesel: 'Дизель',
      pluginHybrid: 'Подключаемый гибрид',
      flexFuel: 'Гибкое топливо',
      cng: 'КПГ',
      lpg: 'ГБО',
    },
    
    // Transmissions
    transmissions: {
      automatic: 'Автоматическая',
      manual: 'Механическая',
      cvt: 'Вариатор',
    },

    // Body Types
    bodyTypes: {
      sedan: 'Седан',
      suv: 'Внедорожник',
      truck: 'Грузовик',
      coupe: 'Купе',
      hatchback: 'Хэтчбек',
      convertible: 'Кабриолет',
      wagon: 'Универсал',
      van: 'Фургон',
      crossover: 'Кроссовер',
    },

    // Drivetrains
    drivetrains: {
      fwd: 'Передний привод',
      rwd: 'Задний привод',
      awd: 'Полный привод',
      fourwd: 'Привод 4x4',
    },

    // Colors
    colors: {
      black: 'Чёрный',
      white: 'Белый',
      silver: 'Серебристый',
      gray: 'Серый',
      red: 'Красный',
      blue: 'Синий',
      green: 'Зелёный',
      brown: 'Коричневый',
      gold: 'Золотой',
      orange: 'Оранжевый',
      purple: 'Фиолетовый',
      yellow: 'Жёлтый',
    },
    
    // Conditions
    conditions: {
      new: 'Новый',
      likeNew: 'Как новый',
      excellent: 'Отличное',
      veryGood: 'Очень хорошее',
      good: 'Хорошее',
      fair: 'Удовлетворительное',
      poor: 'Плохое',
    },
    
    // Features list
    features: {
      airConditioning: 'Кондиционер',
      leatherSeats: 'Кожаные сидения',
      heatedSeats: 'Подогрев сидений',
      sunroof: 'Люк',
      gpsNavigation: 'GPS навигация',
      backupCamera: 'Камера заднего вида',
      bluetooth: 'Bluetooth',
      usbPorts: 'USB порты',
      premiumSound: 'Премиум аудио',
      keylessEntry: 'Бесключевой доступ',
      remoteStart: 'Удаленный запуск',
      cruiseControl: 'Круиз-контроль',
      parkingSensors: 'Парктроник',
      blindSpotMonitoring: 'Контроль слепых зон',
    },
  },

  countries: {
    northMacedonia: 'Северная Македония',
    albania: 'Албания',
    kosovo: 'Косово',
    slovenia: 'Словения',
    latvia: 'Латвия',
    global: 'Глобальный',
    chooseCountry: 'Выберите свою страну',
    changeCountry: 'Изменить страну',
    detectedLocation: 'Определённое местоположение',
    currentSite: 'Текущий сайт',
    localBenefits: 'Местные преимущества',
    localCurrency: 'Местная валюта и цены',
    localLanguages: 'Поддержка родного языка',
    localDealers: 'Местные дилеры и инвентарь',
    regionalFeatures: 'Региональные особенности',
  },

  redirect: {
    welcome: 'Добро пожаловать в CarMarket365!',
    detectedFrom: 'Мы определили, что вы посещаете из',
    redirectMessage: 'Вы будете перенаправлены на наш сайт {country} для лучшего местного опыта, или вы можете выбрать другую страну.',
    continueToSite: 'Перейти на сайт {country}',
    chooseDifferent: 'Выбрать другую страну',
    localBenefitsTitle: 'Местные преимущества для {country}',
    howDetected: 'Как мы это определили?',
    hideDetails: 'Скрыть детали',
    changeAnytime: 'Вы можете изменить предпочтение страны в любое время в заголовке.',
    countrySpecificExperience: 'Каждый сайт страны предлагает локализованный контент, цены и языковые опции для лучшего опыта.',
    adminTestingMode: 'Режим администратора/тестирования',
    adminNotAvailable: 'Режим администратора/тестирования - недоступен для клиентов',
    selectCountryToContinue: 'Пожалуйста, выберите свою страну, чтобы продолжить. Это определит ваш местный сайт, язык и валюту.',
  },

  modals: {
    close: 'Закрыть',
    confirm: 'Подтвердить',
    cancel: 'Отмена',
    save: 'Сохранить',
    delete: 'Удалить',
    contactSeller: 'Связаться с продавцом',
    scheduleTestDrive: 'Запланировать тест-драйв',
    requestFinancing: 'Запросить финансирование',
    reportListing: 'Пожаловаться на объявление',
    shareListng: 'Поделиться объявлением',
    sendMessage: 'Отправить сообщение',
    yourName: 'Ваше имя',
    yourEmail: 'Ваша электронная почта',
    yourPhone: 'Ваш телефон',
    message: 'Сообщение',
    interestedIn: 'Меня интересует',
    preferredTime: 'Предпочтительное время',
    additionalNotes: 'Дополнительные заметки',
  },

  footer: {
    aboutUs: 'Ваш надёжный рынок качественных подержанных автомобилей. Найдите свой идеальный автомобиль среди тысяч объявлений.',
    quickLinks: 'Быстрые ссылки',
    searchCars: 'Поиск автомобилей',
    sellYourCar: 'Продайте свой автомобиль',
    registeredDealers: 'Зарегистрированные дилеры',
    carReviews: 'Обзоры автомобилей',
    support: 'Поддержка',
    contactUs: 'Свяжитесь с нами',
    safetyTips: 'Советы по безопасности',
    dealerSupport: 'Поддержка дилеров',
    faq: 'Часто задаваемые вопросы',
    legal: 'Правовая информация',
    privacyPolicy: 'Политика конфиденциальности',
    termsOfService: 'Условия обслуживания',
    cookiePolicy: 'Политика файлов cookie',
    imprint: 'Выходные данные',
    accessibility: 'Доступность',
    dashboard: 'Панель управления',
    adminPanel: 'Панель администратора',
    dealerDashboard: 'Панель дилера',
    myDashboard: 'Моя панель',
    signInToAccess: 'Войдите для доступа к панели управления',
    followUs: 'Подписывайтесь на нас',
    newsletter: 'Информационная рассылка',
    subscribeNewsletter: 'Подписаться на рассылку',
    emailAddress: 'Адрес электронной почты',
    subscribe: 'Подписаться',
    copyright: 'Авторское право',
    allRightsReserved: 'Все права защищены',
  },

  errors: {
    generic: 'Что-то пошло не так. Пожалуйста, попробуйте ещё раз.',
    network: 'Ошибка сети. Пожалуйста, проверьте своё соединение.',
    notFound: 'Запрашиваемый элемент не найден.',
    unauthorized: 'У вас нет разрешения на доступ к этому ресурсу.',
    forbidden: 'Доступ к этому ресурсу запрещён.',
    serverError: 'Ошибка сервера. Пожалуйста, попробуйте позже.',
    validation: 'Пожалуйста, проверьте свои данные и попробуйте ещё раз.',
    required: 'Это поле обязательно.',
    invalidEmail: 'Пожалуйста, введите действительный адрес электронной почты.',
    invalidPhone: 'Пожалуйста, введите действительный номер телефона.',
    passwordTooShort: 'Пароль должен быть длиной не менее 8 символов.',
    passwordMismatch: 'Пароли не совпадают.',
    fileTooBig: 'Размер файла слишком большой.',
    invalidFileType: 'Недопустимый тип файла.',
    noInternetConnection: 'Нет интернет-соединения.',
    sessionExpired: 'Ваша сессия истекла. Пожалуйста, войдите снова.',
  },

  success: {
    saved: 'Успешно сохранено!',
    updated: 'Успешно обновлено!',
    deleted: 'Успешно удалено!',
    sent: 'Успешно отправлено!',
    published: 'Успешно опубликовано!',
    registered: 'Успешно зарегистрирован!',
    loggedIn: 'Успешный вход в систему!',
    loggedOut: 'Успешный выход из системы!',
    passwordReset: 'Письмо для сброса пароля отправлено!',
    subscribed: 'Успешно подписан!',
    contactSent: 'Контактное сообщение отправлено!',
    favoriteAdded: 'Добавлено в избранное!',
    favoriteRemoved: 'Удалено из избранного!',
  },

  admin: {
    panel: 'Панель администратора',
    dashboard: 'Панель управления администратора',
  },

  pages: {
    helpCenter: 'Центр поддержки',
    feedback: 'Обратная связь',
    disclaimer: 'Отказ от ответственности',
    carInsurance: 'Автострахование',
    underConstruction: 'В разработке',
    underConstructionMessage: 'Данная страница находится в разработке. Мы усердно работаем над созданием потрясающих функций. Пожалуйста, зайдите позже или продолжите изучать нашу главную страницу.',
    backToHome: 'Вернуться на главную',
    contactUs: 'Свяжитесь с нами',
    
    // Условия обслуживания
    termsOfService: {
      title: 'Условия обслуживания',
      subtitle: 'Правовые условия использования нашей платформы автомобильного рынка.',
      backToHome: 'Вернуться на главную',
      termsAndConditions: 'Условия и положения',
      termsDescription: 'Пожалуйста, внимательно ознакомьтесь с этими условиями перед использованием нашей платформы.',
      overviewText: 'Данные Условия обслуживания регулируют использование вами платформы CarMarket365 и определяют права и обязанности всех пользователей. Получая доступ к нашей платформе, вы соглашаетесь соблюдать эти условия.',
      userResponsibilities: 'Обязанности пользователя',
      userResponsibilitiesList: [
        'Предоставлять точную информацию',
        'Поддерживать уважительное общение',
        'Соблюдать все применимые законы',
        'Защищать учетные данные вашего аккаунта'
      ],
      platformRules: 'Правила платформы',
      platformRulesList: [
        'Запрещены мошеннические объявления',
        'Честные описания транспортных средств',
        'Профессиональное общение',
        'Уважение к конфиденциальности других пользователей'
      ],
      serviceLimitations: 'Ограничения услуг',
      serviceLimitationsList: [
        'Доступность платформы не гарантируется',
        'Техническое обслуживание может вызвать простой',
        'Ограниченная ответственность за действия пользователей',
        'Отсутствие гарантий на контент третьих лиц'
      ],
      disputeResolution: 'Разрешение споров',
      disputeResolutionList: [
        'Поощряется прямое общение',
        'Доступно посредничество платформы',
        'Определены процедуры эскалации',
        'Сохраняются правовые средства защиты'
      ],
      additionalTerms: 'Дополнительные важные условия',
      additionalTermsDescription: 'Ключевые положения, регулирующие использование нашей платформы.',
      accountManagement: 'Управление аккаунтом',
      accountManagementList: [
        'Один аккаунт на человека',
        'Требования к безопасности пароля',
        'Политики приостановки аккаунта',
        'Хранение данных после прекращения'
      ],
      intellectualProperty: 'Интеллектуальная собственность',
      intellectualPropertyList: [
        'Владение контентом платформы',
        'Права на пользовательский контент',
        'Рекомендации по использованию торговых марок',
        'Политики нарушения авторских прав'
      ],
      questionsAboutTerms: 'Вопросы об этих условиях?',
      questionsText: 'Если у вас есть вопросы об этих условиях или вам нужны разъяснения по каким-либо положениям, пожалуйста, обратитесь к нашей юридической команде по адресу legal@carmarket365.com',
      returnToPlatform: 'Вернуться на платформу',
      contactLegalTeam: 'Связаться с юридической командой'
    },

    // Политика конфиденциальности
    privacyPolicy: {
      title: 'Политика конфиденциальности',
      subtitle: 'Ваша конфиденциальность важна для нас. Узнайте, как мы собираем, используем и защищаем вашу личную информацию.',
      backToHome: 'Вернуться на главную',
      ourPrivacyCommitment: 'Наши обязательства по конфиденциальности',
      commitmentDescription: 'В CarMarket365 мы привержены защите вашей конфиденциальности и обеспечению безопасности вашей личной информации.',
      overviewText: 'Данная политика конфиденциальности объясняет, как мы собираем, используем, раскрываем и защищаем вашу информацию при использовании нашей платформы автомобильного рынка. Мы привержены поддержанию высочайших стандартов защиты конфиденциальности и безопасности данных.',
      dataSecurity: 'Безопасность данных',
      dataSecurityList: [
        'Шифрование отраслевого стандарта',
        'Безопасная передача данных',
        'Регулярные аудиты безопасности',
