import { gql } from '@apollo/client';

// SEO Keywords Operations
export const GET_SEO_KEYWORDS = gql`
  query GetSEOKeywords($filters: SEOKeywordFilters) {
    seoKeywords(filters: $filters) {
      id
      keyword
      ranking
      previousRanking
      searchVolume
      difficulty
      cpc
      url
      targetPage
      category
      lastUpdated
      rankingHistory {
        date
        ranking
      }
    }
  }
`;

export const CREATE_SEO_KEYWORD = gql`
  mutation CreateSEOKeyword($input: CreateSEOKeywordInput!) {
    createSEOKeyword(input: $input) {
      id
      keyword
      category
      url
      createdAt
    }
  }
`;

export const UPDATE_SEO_KEYWORD = gql`
  mutation UpdateSEOKeyword($id: ID!, $input: UpdateSEOKeywordInput!) {
    updateSEOKeyword(id: $id, input: $input) {
      id
      keyword
      ranking
      category
      url
      updatedAt
    }
  }
`;

export const DELETE_SEO_KEYWORD = gql`
  mutation DeleteSEOKeyword($id: ID!) {
    deleteSEOKeyword(id: $id)
  }
`;

// Meta Data Operations
export const GET_SEO_METADATA = gql`
  query GetSEOMetadata($filters: SEOMetadataFilters) {
    seoMetadata(filters: $filters) {
      id
      url
      title
      description
      titleLength
      descriptionLength
      status
      type
      lastModified
      autoGenerated
      clicks
      impressions
      ctr
    }
  }
`;

export const UPDATE_SEO_METADATA = gql`
  mutation UpdateSEOMetadata($id: ID!, $input: UpdateSEOMetadataInput!) {
    updateSEOMetadata(id: $id, input: $input) {
      id
      url
      title
      description
      updatedAt
    }
  }
`;

export const BULK_UPDATE_METADATA = gql`
  mutation BulkUpdateMetadata($input: BulkUpdateMetadataInput!) {
    bulkUpdateMetadata(input: $input) {
      updatedCount
      errors {
        url
        message
      }
    }
  }
`;

export const AUTO_GENERATE_METADATA = gql`
  mutation AutoGenerateMetadata($input: AutoGenerateMetadataInput!) {
    autoGenerateMetadata(input: $input) {
      generatedCount
      results {
        url
        title
        description
      }
    }
  }
`;

// Competitor Analysis Operations
export const GET_COMPETITORS = gql`
  query GetCompetitors {
    competitors {
      id
      name
      domain
      organicKeywords
      organicTraffic
      averageRanking
      backlinks
      lastAnalyzed
      change30d {
        keywords
        traffic
        ranking
      }
      topKeywords {
        keyword
        ranking
        volume
        ourRanking
      }
      trafficTrend {
        month
        traffic
      }
    }
  }
`;

export const ADD_COMPETITOR = gql`
  mutation AddCompetitor($input: AddCompetitorInput!) {
    addCompetitor(input: $input) {
      id
      name
      domain
      createdAt
    }
  }
`;

export const GET_KEYWORD_GAPS = gql`
  query GetKeywordGaps($competitorId: ID!) {
    keywordGaps(competitorId: $competitorId) {
      keyword
      competitorRanking
      ourRanking
      volume
      difficulty
      opportunity
    }
  }
`;

// SEO Analytics Operations
export const GET_SEO_ANALYTICS = gql`
  query GetSEOAnalytics($timeRange: String!) {
    seoAnalytics(timeRange: $timeRange) {
      organicTraffic {
        date
        traffic
        clicks
        impressions
        ctr
        avgPosition
      }
      topPages {
        url
        pageTitle
        clicks
        impressions
        ctr
        avgPosition
        change
      }
      topQueries {
        query
        clicks
        impressions
        ctr
        position
        change
      }
      deviceBreakdown {
        device
        clicks
        impressions
        ctr
      }
      countryBreakdown {
        country
        clicks
        impressions
        ctr
      }
    }
  }
`;

// Technical SEO Operations
export const GET_SITEMAPS = gql`
  query GetSitemaps {
    sitemaps {
      id
      name
      url
      type
      urlCount
      lastGenerated
      lastSubmitted
      status
      fileSize
      errors
    }
  }
`;

export const GENERATE_SITEMAP = gql`
  mutation GenerateSitemap($id: ID!) {
    generateSitemap(id: $id) {
      id
      status
      urlCount
      lastGenerated
    }
  }
`;

export const SUBMIT_SITEMAP_TO_GSC = gql`
  mutation SubmitSitemapToGSC($id: ID!) {
    submitSitemapToGSC(id: $id) {
      id
      lastSubmitted
      status
    }
  }
`;

export const GET_REDIRECT_RULES = gql`
  query GetRedirectRules {
    redirectRules {
      id
      source
      target
      statusCode
      type
      createdAt
      lastHit
      hitCount
      isActive
    }
  }
`;

export const CREATE_REDIRECT_RULE = gql`
  mutation CreateRedirectRule($input: CreateRedirectRuleInput!) {
    createRedirectRule(input: $input) {
      id
      source
      target
      statusCode
      type
      isActive
      createdAt
    }
  }
`;

export const GET_CRAWL_ERRORS = gql`
  query GetCrawlErrors {
    crawlErrors {
      id
      url
      errorType
      statusCode
      message
      firstDetected
      lastDetected
      occurrences
      fixed
    }
  }
`;

export const GET_TECHNICAL_ISSUES = gql`
  query GetTechnicalIssues {
    technicalIssues {
      id
      type
      severity
      title
      description
      affectedUrls
      recommendation
      estimatedImpact
      fixComplexity
    }
  }
`;

export const GET_ROBOTS_TXT = gql`
  query GetRobotsTxt {
    robotsTxt {
      content
      lastModified
      isValid
      errors
    }
  }
`;

export const UPDATE_ROBOTS_TXT = gql`
  mutation UpdateRobotsTxt($content: String!) {
    updateRobotsTxt(content: $content) {
      content
      lastModified
      isValid
      errors
    }
  }
`;

// SEO Task Management Operations
export const GET_SEO_TASKS = gql`
  query GetSEOTasks($filters: SEOTaskFilters) {
    seoTasks(filters: $filters) {
      id
      title
      description
      type
      category
      status
      priority
      schedule {
        frequency
        time
        days
      }
      nextRun
      lastRun
      lastResult
      progress
      createdAt
      estimatedDuration
      owner
    }
  }
`;

export const CREATE_SEO_TASK = gql`
  mutation CreateSEOTask($input: CreateSEOTaskInput!) {
    createSEOTask(input: $input) {
      id
      title
      type
      category
      status
      createdAt
    }
  }
`;

export const UPDATE_SEO_TASK = gql`
  mutation UpdateSEOTask($id: ID!, $input: UpdateSEOTaskInput!) {
    updateSEOTask(id: $id, input: $input) {
      id
      title
      status
      updatedAt
    }
  }
`;

export const RUN_SEO_TASK = gql`
  mutation RunSEOTask($id: ID!) {
    runSEOTask(id: $id) {
      id
      status
      startedAt
    }
  }
`;

export const PAUSE_SEO_TASK = gql`
  mutation PauseSEOTask($id: ID!) {
    pauseSEOTask(id: $id) {
      id
      status
      pausedAt
    }
  }
`;

export const GET_TASK_EXECUTIONS = gql`
  query GetTaskExecutions {
    taskExecutions {
      id
      taskId
      taskTitle
      startTime
      endTime
      status
      result
      logs
      duration
      errorMessage
    }
  }
`;

export const GET_AUTOMATION_RULES = gql`
  query GetAutomationRules {
    automationRules {
      id
      name
      trigger
      condition
      action
      isActive
      lastTriggered
      triggerCount
      createdAt
    }
  }
`;

export const CREATE_AUTOMATION_RULE = gql`
  mutation CreateAutomationRule($input: CreateAutomationRuleInput!) {
    createAutomationRule(input: $input) {
      id
      name
      trigger
      condition
      action
      isActive
      createdAt
    }
  }
`;

export const UPDATE_AUTOMATION_RULE = gql`
  mutation UpdateAutomationRule($id: ID!, $input: UpdateAutomationRuleInput!) {
    updateAutomationRule(id: $id, input: $input) {
      id
      name
      isActive
      updatedAt
    }
  }
`;

// SEO Health Score Operations
export const GET_SEO_HEALTH_SCORE = gql`
  query GetSEOHealthScore {
    seoHealthScore {
      overall
      technical
      content
      performance
      mobile
      lastUpdated
      recommendations {
        type
        title
        description
        priority
        impact
      }
    }
  }
`;

// SEO Audit Operations
export const RUN_SEO_AUDIT = gql`
  mutation RunSEOAudit($input: RunSEOAuditInput!) {
    runSEOAudit(input: $input) {
      id
      status
      startedAt
      estimatedCompletion
    }
  }
`;

export const GET_SEO_AUDIT_RESULTS = gql`
  query GetSEOAuditResults($auditId: ID!) {
    seoAuditResults(auditId: $auditId) {
      id
      status
      completedAt
      issues {
        type
        severity
        title
        description
        affectedUrls
        recommendation
        priority
        fixComplexity
      }
      summary {
        totalIssues
        criticalIssues
        warningIssues
        infoIssues
        pagesScanned
      }
    }
  }
`;

// TypeScript interfaces for the operations
export interface SEOKeyword {
  id: string;
  keyword: string;
  ranking: number;
  previousRanking: number;
  searchVolume: number;
  difficulty: number;
  cpc: number;
  url: string;
  targetPage: string;
  category: 'brand' | 'model' | 'location' | 'general';
  lastUpdated: string;
  rankingHistory: Array<{
    date: string;
    ranking: number;
  }>;
}

export interface SEOMetadata {
  id: string;
  url: string;
  title: string;
  description: string;
  titleLength: number;
  descriptionLength: number;
  status: 'good' | 'warning' | 'error';
  type: 'car-listing' | 'category' | 'homepage' | 'dealer' | 'other';
  lastModified: string;
  autoGenerated: boolean;
  clicks: number;
  impressions: number;
  ctr: number;
}

export interface Competitor {
  id: string;
  name: string;
  domain: string;
  organicKeywords: number;
  organicTraffic: number;
  averageRanking: number;
  backlinks: number;
  lastAnalyzed: string;
  change30d: {
    keywords: number;
    traffic: number;
    ranking: number;
  };
  topKeywords: Array<{
    keyword: string;
    ranking: number;
    volume: number;
    ourRanking?: number;
  }>;
  trafficTrend: Array<{
    month: string;
    traffic: number;
  }>;
}

export interface SEOTask {
  id: string;
  title: string;
  description: string;
  type: 'automated' | 'manual' | 'recurring';
  category: 'keyword_tracking' | 'content_optimization' | 'technical_audit' | 'reporting' | 'competitor_analysis';
  status: 'active' | 'paused' | 'completed' | 'failed';
  priority: 'high' | 'medium' | 'low';
  schedule?: {
    frequency: 'daily' | 'weekly' | 'monthly';
    time: string;
    days?: string[];
  };
  nextRun?: string;
  lastRun?: string;
  lastResult?: string;
  progress?: number;
  createdAt: string;
  estimatedDuration: string;
  owner: string;
}

export interface SEOHealthScore {
  overall: number;
  technical: number;
  content: number;
  performance: number;
  mobile: number;
  lastUpdated: string;
  recommendations: Array<{
    type: string;
    title: string;
    description: string;
    priority: 'high' | 'medium' | 'low';
    impact: 'high' | 'medium' | 'low';
  }>;
}