import { useState } from 'react';
import { 
  Search, 
  Edit, 
  Eye, 
  Settings, 
  Download, 
  Upload,
  CheckCircle, 
  AlertTriangle, 
  XCircle,
  Wand2,
  Copy,
  ExternalLink,
  Filter
} from 'lucide-react';
import { Button } from '../ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '../ui/card';
import { Input } from '../ui/input';
import { Badge } from '../ui/badge';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../ui/table';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '../ui/dialog';
import { Label } from '../ui/label';
import { Textarea } from '../ui/textarea';
import { Progress } from '../ui/progress';
import { Checkbox } from '../ui/checkbox';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../ui/tabs';

// Types for meta data
interface MetaDataItem {
  id: string;
  url: string;
  title: string;
  description: string;
  titleLength: number;
  descriptionLength: number;
  status: 'good' | 'warning' | 'error';
  type: 'car-listing' | 'category' | 'homepage' | 'dealer' | 'other';
  lastModified: string;
  autoGenerated: boolean;
  clicks: number;
  impressions: number;
  ctr: number;
}

interface MetaTemplate {
  id: string;
  name: string;
  type: 'car-listing' | 'category' | 'dealer' | 'general';
  titleTemplate: string;
  descriptionTemplate: string;
  variables: string[];
}

export default function MetaDataManagement() {
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [typeFilter, setTypeFilter] = useState('all');
  const [selectedItems, setSelectedItems] = useState<string[]>([]);
  const [isBulkEditOpen, setIsBulkEditOpen] = useState(false);
  const [isTemplateDialogOpen, setIsTemplateDialogOpen] = useState(false);
  const [activeTab, setActiveTab] = useState('metadata');

  // Mock meta data
  const metaDataItems: MetaDataItem[] = [
    {
      id: '1',
      url: '/cars/123',
      title: '2020 BMW X5 xDrive40i - Premium SUV for Sale | CarMarket365',
      description: 'Discover this excellent 2020 BMW X5 xDrive40i with low mileage, premium features, and full service history. Contact dealer for more information.',
      titleLength: 65,
      descriptionLength: 143,
      status: 'good',
      type: 'car-listing',
      lastModified: '2024-01-20',
      autoGenerated: true,
      clicks: 245,
      impressions: 5800,
      ctr: 4.2
    },
    {
      id: '2',
      url: '/cars',
      title: 'Used Cars for Sale in Macedonia - Best Prices & Quality Vehicles | CarMarket365',
      description: 'Find the perfect used car in Macedonia. Browse thousands of quality vehicles from trusted dealers with competitive prices and comprehensive vehicle history reports.',
      titleLength: 78,
      descriptionLength: 158,
      status: 'warning',
      type: 'category',
      lastModified: '2024-01-18',
      autoGenerated: false,
      clicks: 1250,
      impressions: 28500,
      ctr: 4.4
    },
    {
      id: '3',
      url: '/cars/456',
      title: 'Audi A4 2019',
      description: 'Car for sale',
      titleLength: 14,
      descriptionLength: 13,
      status: 'error',
      type: 'car-listing',
      lastModified: '2024-01-15',
      autoGenerated: false,
      clicks: 15,
      impressions: 890,
      ctr: 1.7
    },
    {
      id: '4',
      url: '/registered-dealers',
      title: 'Registered Car Dealers in Macedonia - Trusted Automotive Partners',
      description: 'Browse our network of verified car dealers across Macedonia. Find reputable dealers with quality vehicles, competitive prices, and excellent customer service.',
      titleLength: 69,
      descriptionLength: 151,
      status: 'good',
      type: 'dealer',
      lastModified: '2024-01-19',
      autoGenerated: false,
      clicks: 380,
      impressions: 7200,
      ctr: 5.3
    },
    {
      id: '5',
      url: '/cars/789',
      title: 'Mercedes-Benz E-Class 2021 - Luxury Sedan with Premium Features',
      description: 'Experience luxury with this 2021 Mercedes-Benz E-Class. Features leather interior, advanced safety systems, and low mileage. Perfect condition.',
      titleLength: 67,
      descriptionLength: 141,
      status: 'good',
      type: 'car-listing',
      lastModified: '2024-01-21',
      autoGenerated: true,
      clicks: 156,
      impressions: 3200,
      ctr: 4.9
    }
  ];

  // Mock templates
  const templates: MetaTemplate[] = [
    {
      id: '1',
      name: 'Car Listing Template',
      type: 'car-listing',
      titleTemplate: '{year} {make} {model} - {condition} {bodyType} for Sale | CarMarket365',
      descriptionTemplate: 'Discover this {condition} {year} {make} {model} with {mileage} km, {features}. {dealerName} offers competitive pricing and quality service.',
      variables: ['year', 'make', 'model', 'condition', 'bodyType', 'mileage', 'features', 'dealerName']
    },
    {
      id: '2',
      name: 'Category Page Template',
      type: 'category',
      titleTemplate: '{make} Cars for Sale in {location} | Best Prices | CarMarket365',
      descriptionTemplate: 'Browse {make} vehicles in {location}. Find quality used cars with verified history, competitive pricing, and trusted dealers.',
      variables: ['make', 'location']
    },
    {
      id: '3',
      name: 'Dealer Profile Template',
      type: 'dealer',
      titleTemplate: '{dealerName} - Car Dealer in {location} | CarMarket365',
      descriptionTemplate: '{dealerName} in {location} offers quality used cars with professional service. Browse their inventory and contact for more information.',
      variables: ['dealerName', 'location']
    }
  ];

  const filteredItems = metaDataItems.filter(item => {
    const matchesSearch = item.url.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         item.title.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = statusFilter === 'all' || item.status === statusFilter;
    const matchesType = typeFilter === 'all' || item.type === typeFilter;
    return matchesSearch && matchesStatus && matchesType;
  });

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'good':
        return <Badge variant="default" className="bg-green-100 text-green-700 border-green-300"><CheckCircle className="h-3 w-3 mr-1" />Good</Badge>;
      case 'warning':
        return <Badge variant="outline" className="border-yellow-500 text-yellow-700"><AlertTriangle className="h-3 w-3 mr-1" />Warning</Badge>;
      case 'error':
        return <Badge variant="destructive"><XCircle className="h-3 w-3 mr-1" />Error</Badge>;
      default:
        return <Badge variant="secondary">{status}</Badge>;
    }
  };

  const getTypeBadge = (type: string) => {
    const colors = {
      'car-listing': 'bg-blue-100 text-blue-700',
      'category': 'bg-green-100 text-green-700',
      'homepage': 'bg-purple-100 text-purple-700',
      'dealer': 'bg-orange-100 text-orange-700',
      'other': 'bg-gray-100 text-gray-700'
    };
    
    return (
      <Badge variant="secondary" className={colors[type as keyof typeof colors] || 'bg-gray-100 text-gray-700'}>
        {type.replace('-', ' ').replace(/\b\w/g, l => l.toUpperCase())}
      </Badge>
    );
  };

  const getTitleLengthStatus = (length: number) => {
    if (length < 30) return { status: 'error', message: 'Too short' };
    if (length > 60) return { status: 'warning', message: 'Too long' };
    return { status: 'good', message: 'Good length' };
  };

  const getDescriptionLengthStatus = (length: number) => {
    if (length < 120) return { status: 'warning', message: 'Could be longer' };
    if (length > 160) return { status: 'error', message: 'Too long' };
    return { status: 'good', message: 'Good length' };
  };

  const handleSelectAll = (checked: boolean) => {
    if (checked) {
      setSelectedItems(filteredItems.map(item => item.id));
    } else {
      setSelectedItems([]);
    }
  };

  const handleItemSelect = (itemId: string, checked: boolean) => {
    if (checked) {
      setSelectedItems([...selectedItems, itemId]);
    } else {
      setSelectedItems(selectedItems.filter(id => id !== itemId));
    }
  };

  const generatePreview = (item: MetaDataItem) => {
    return (
      <div className="bg-white border rounded-lg p-4 max-w-2xl">
        <div className="text-sm text-green-700 mb-1">
          carmarket365.com {item.url}
        </div>
        <div className="text-blue-600 hover:underline cursor-pointer text-lg mb-1 leading-tight">
          {item.title}
        </div>
        <div className="text-gray-600 text-sm leading-relaxed">
          {item.description}
        </div>
      </div>
    );
  };

  // Summary statistics
  const totalItems = metaDataItems.length;
  const goodItems = metaDataItems.filter(item => item.status === 'good').length;
  const warningItems = metaDataItems.filter(item => item.status === 'warning').length;
  const errorItems = metaDataItems.filter(item => item.status === 'error').length;
  const autoGeneratedCount = metaDataItems.filter(item => item.autoGenerated).length;

  return (
    <div className="space-y-6">
      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4">
        <Card>
          <CardContent className="pt-4">
            <div className="text-center">
              <p className="text-2xl font-bold">{totalItems}</p>
              <p className="text-sm text-muted-foreground">Total Pages</p>
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardContent className="pt-4">
            <div className="text-center">
              <p className="text-2xl font-bold text-green-600">{goodItems}</p>
              <p className="text-sm text-muted-foreground">Good</p>
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardContent className="pt-4">
            <div className="text-center">
              <p className="text-2xl font-bold text-yellow-600">{warningItems}</p>
              <p className="text-sm text-muted-foreground">Warnings</p>
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardContent className="pt-4">
            <div className="text-center">
              <p className="text-2xl font-bold text-red-600">{errorItems}</p>
              <p className="text-sm text-muted-foreground">Errors</p>
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardContent className="pt-4">
            <div className="text-center">
              <p className="text-2xl font-bold text-blue-600">{autoGeneratedCount}</p>
              <p className="text-sm text-muted-foreground">Auto-Generated</p>
            </div>
          </CardContent>
        </Card>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-6">
        <TabsList>
          <TabsTrigger value="metadata">Meta Data</TabsTrigger>
          <TabsTrigger value="templates">Templates</TabsTrigger>
          <TabsTrigger value="bulk-tools">Bulk Tools</TabsTrigger>
        </TabsList>

        <TabsContent value="metadata" className="space-y-6">
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle>Meta Data Overview</CardTitle>
                  <CardDescription>Manage page titles and descriptions for better search visibility</CardDescription>
                </div>
                <div className="flex gap-2">
                  <Button variant="outline" size="sm">
                    <Download className="h-4 w-4 mr-2" />
                    Export
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => setIsBulkEditOpen(true)}>
                    Bulk Edit ({selectedItems.length})
                  </Button>
                  <Button size="sm">
                    <Wand2 className="h-4 w-4 mr-2" />
                    Auto-Generate
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              {/* Filters */}
              <div className="flex flex-col sm:flex-row gap-4 mb-6">
                <div className="relative flex-1">
                  <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                  <Input 
                    placeholder="Search URLs or titles..." 
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    className="pl-10" 
                  />
                </div>
                <Select value={statusFilter} onValueChange={setStatusFilter}>
                  <SelectTrigger className="w-full sm:w-32">
                    <SelectValue placeholder="Status" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Status</SelectItem>
                    <SelectItem value="good">Good</SelectItem>
                    <SelectItem value="warning">Warning</SelectItem>
                    <SelectItem value="error">Error</SelectItem>
                  </SelectContent>
                </Select>
                <Select value={typeFilter} onValueChange={setTypeFilter}>
                  <SelectTrigger className="w-full sm:w-40">
                    <SelectValue placeholder="Type" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Types</SelectItem>
                    <SelectItem value="car-listing">Car Listing</SelectItem>
                    <SelectItem value="category">Category</SelectItem>
                    <SelectItem value="dealer">Dealer</SelectItem>
                    <SelectItem value="other">Other</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="w-12">
                      <Checkbox 
                        checked={selectedItems.length === filteredItems.length && filteredItems.length > 0}
                        onCheckedChange={handleSelectAll}
                      />
                    </TableHead>
                    <TableHead>URL</TableHead>
                    <TableHead>Title</TableHead>
                    <TableHead>Description</TableHead>
                    <TableHead>Length</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Performance</TableHead>
                    <TableHead>Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredItems.map((item) => {
                    const titleStatus = getTitleLengthStatus(item.titleLength);
                    const descStatus = getDescriptionLengthStatus(item.descriptionLength);
                    
                    return (
                      <TableRow key={item.id}>
                        <TableCell>
                          <Checkbox 
                            checked={selectedItems.includes(item.id)}
                            onCheckedChange={(checked) => handleItemSelect(item.id, checked as boolean)}
                          />
                        </TableCell>
                        <TableCell className="max-w-xs">
                          <div className="truncate font-mono text-sm">{item.url}</div>
                          {getTypeBadge(item.type)}
                        </TableCell>
                        <TableCell className="max-w-sm">
                          <div className="space-y-1">
                            <div className="truncate font-medium">{item.title}</div>
                            <div className="flex items-center gap-2">
                              <Progress value={(item.titleLength / 60) * 100} className="w-20 h-1" />
                              <span className="text-xs text-muted-foreground">
                                {item.titleLength}/60
                              </span>
                              <Badge 
                                variant={titleStatus.status === 'good' ? 'default' : titleStatus.status === 'warning' ? 'outline' : 'destructive'}
                                className="text-xs"
                              >
                                {titleStatus.message}
                              </Badge>
                            </div>
                          </div>
                        </TableCell>
                        <TableCell className="max-w-md">
                          <div className="space-y-1">
                            <div className="truncate text-sm text-muted-foreground">{item.description}</div>
                            <div className="flex items-center gap-2">
                              <Progress value={(item.descriptionLength / 160) * 100} className="w-20 h-1" />
                              <span className="text-xs text-muted-foreground">
                                {item.descriptionLength}/160
                              </span>
                              <Badge 
                                variant={descStatus.status === 'good' ? 'default' : descStatus.status === 'warning' ? 'outline' : 'destructive'}
                                className="text-xs"
                              >
                                {descStatus.message}
                              </Badge>
                            </div>
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="text-xs space-y-1">
                            <div>T: {item.titleLength}</div>
                            <div>D: {item.descriptionLength}</div>
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="space-y-1">
                            {getStatusBadge(item.status)}
                            {item.autoGenerated && (
                              <Badge variant="outline" className="text-xs">
                                <Wand2 className="h-2 w-2 mr-1" />Auto
                              </Badge>
                            )}
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="text-xs space-y-1">
                            <div>CTR: {item.ctr}%</div>
                            <div>{item.clicks} clicks</div>
                            <div className="text-muted-foreground">{item.impressions.toLocaleString()} imp</div>
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="flex gap-1">
                            <Dialog>
                              <DialogTrigger asChild>
                                <Button variant="ghost" size="sm">
                                  <Eye className="h-4 w-4" />
                                </Button>
                              </DialogTrigger>
                              <DialogContent className="max-w-3xl">
                                <DialogHeader>
                                  <DialogTitle>Search Result Preview</DialogTitle>
                                </DialogHeader>
                                <div className="space-y-4">
                                  <div>
                                    <Label className="text-sm font-medium">How it appears in search results:</Label>
                                    <div className="mt-2">
                                      {generatePreview(item)}
                                    </div>
                                  </div>
                                  <div className="grid grid-cols-2 gap-4">
                                    <div>
                                      <Label>Title ({item.titleLength}/60 characters)</Label>
                                      <div className="mt-1 p-3 bg-muted rounded border">
                                        {item.title}
                                      </div>
                                    </div>
                                    <div>
                                      <Label>Description ({item.descriptionLength}/160 characters)</Label>
                                      <div className="mt-1 p-3 bg-muted rounded border">
                                        {item.description}
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </DialogContent>
                            </Dialog>
                            <Button variant="ghost" size="sm">
                              <Edit className="h-4 w-4" />
                            </Button>
                            <Button variant="ghost" size="sm">
                              <Copy className="h-4 w-4" />
                            </Button>
                            <Button variant="ghost" size="sm">
                              <ExternalLink className="h-4 w-4" />
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="templates" className="space-y-6">
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle>Meta Data Templates</CardTitle>
                  <CardDescription>Create and manage templates for automated meta data generation</CardDescription>
                </div>
                <Dialog open={isTemplateDialogOpen} onOpenChange={setIsTemplateDialogOpen}>
                  <DialogTrigger asChild>
                    <Button>Create Template</Button>
                  </DialogTrigger>
                  <DialogContent>
                    <DialogHeader>
                      <DialogTitle>Create Meta Data Template</DialogTitle>
                    </DialogHeader>
                    <div className="space-y-4">
                      <div>
                        <Label>Template Name</Label>
                        <Input placeholder="e.g., Car Listing Template" />
                      </div>
                      <div>
                        <Label>Page Type</Label>
                        <Select>
                          <SelectTrigger>
                            <SelectValue placeholder="Select type" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="car-listing">Car Listing</SelectItem>
                            <SelectItem value="category">Category Page</SelectItem>
                            <SelectItem value="dealer">Dealer Profile</SelectItem>
                            <SelectItem value="general">General Page</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                      <div>
                        <Label>Title Template</Label>
                        <Input placeholder="{year} {make} {model} - {condition} | CarMarket365" />
                        <p className="text-xs text-muted-foreground mt-1">
                          Use variables like {'{year}'}, {'{make}'}, {'{model}'} for dynamic content
                        </p>
                      </div>
                      <div>
                        <Label>Description Template</Label>
                        <Textarea 
                          placeholder="Discover this {condition} {year} {make} {model} with {mileage} km..."
                          className="min-h-[80px]"
                        />
                      </div>
                    </div>
                  </DialogContent>
                </Dialog>
              </div>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {templates.map((template) => (
                  <Card key={template.id} className="border">
                    <CardContent className="pt-4">
                      <div className="flex items-start justify-between">
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-2">
                            <h4 className="font-semibold">{template.name}</h4>
                            {getTypeBadge(template.type)}
                          </div>
                          <div className="space-y-2 text-sm">
                            <div>
                              <span className="font-medium">Title:</span>
                              <span className="ml-2 text-muted-foreground font-mono">{template.titleTemplate}</span>
                            </div>
                            <div>
                              <span className="font-medium">Description:</span>
                              <span className="ml-2 text-muted-foreground font-mono">{template.descriptionTemplate}</span>
                            </div>
                            <div>
                              <span className="font-medium">Variables:</span>
                              <div className="ml-2 flex flex-wrap gap-1 mt-1">
                                {template.variables.map((variable) => (
                                  <Badge key={variable} variant="outline" className="text-xs">
                                    {'{' + variable + '}'}
                                  </Badge>
                                ))}
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="flex gap-2">
                          <Button variant="outline" size="sm">
                            <Edit className="h-4 w-4" />
                          </Button>
                          <Button variant="outline" size="sm">
                            Apply
                          </Button>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="bulk-tools" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Bulk Operations</CardTitle>
              <CardDescription>Perform bulk operations on meta data</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <Card>
                  <CardContent className="pt-4">
                    <div className="text-center space-y-2">
                      <Wand2 className="h-8 w-8 mx-auto text-blue-500" />
                      <h3 className="font-semibold">Auto-Generate</h3>
                      <p className="text-sm text-muted-foreground">
                        Automatically generate meta data for pages using templates
                      </p>
                      <Button size="sm">Generate</Button>
                    </div>
                  </CardContent>
                </Card>
                
                <Card>
                  <CardContent className="pt-4">
                    <div className="text-center space-y-2">
                      <Upload className="h-8 w-8 mx-auto text-green-500" />
                      <h3 className="font-semibold">Bulk Import</h3>
                      <p className="text-sm text-muted-foreground">
                        Import meta data from CSV file for bulk updates
                      </p>
                      <Button size="sm" variant="outline">Import</Button>
                    </div>
                  </CardContent>
                </Card>
                
                <Card>
                  <CardContent className="pt-4">
                    <div className="text-center space-y-2">
                      <Download className="h-8 w-8 mx-auto text-purple-500" />
                      <h3 className="font-semibold">Export Data</h3>
                      <p className="text-sm text-muted-foreground">
                        Export meta data to CSV for external editing
                      </p>
                      <Button size="sm" variant="outline">Export</Button>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}